// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCabBioDAB9jGZqpQaktQbhLfk-HqfgqFg',
    appId: '1:1041495090739:web:19a07740e258be9d25e546',
    messagingSenderId: '1041495090739',
    projectId: 'himitsu-firebase',
    authDomain: 'himitsu-firebase.firebaseapp.com',
    storageBucket: 'himitsu-firebase.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxQ3Y0Kuq1yUHe2ilcpXraMfkZsiiLRow',
    appId: '1:1041495090739:android:9b797addb55ed15e25e546',
    messagingSenderId: '1041495090739',
    projectId: 'himitsu-firebase',
    storageBucket: 'himitsu-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOl5ICflxWTHyLfSovoqhbaZl49AWtAv8',
    appId: '1:1041495090739:ios:da8c1f07c465036e25e546',
    messagingSenderId: '1041495090739',
    projectId: 'himitsu-firebase',
    storageBucket: 'himitsu-firebase.appspot.com',
    iosBundleId: 'xyz.jack3n1gm4.himitsuApp',
  );
}
